https://www.perplexity.ai/search/0eafd6c8-1230-4d5d-9553-446ea1f18997

In [1]:
#學生成績單

import numpy as np
import pandas as pd

scores = np.random.randint(50, 101, size=(50, 5))
scores

array([[ 82,  61,  99,  69,  84],
       [ 52,  81,  57,  54,  54],
       [ 69,  99,  83,  65,  57],
       [ 56,  87,  73,  56,  97],
       [ 59,  50,  75,  70,  99],
       [ 54,  61,  75,  97,  80],
       [ 62,  94,  89,  66, 100],
       [ 99,  91,  88,  66,  78],
       [ 91,  54,  93,  72,  89],
       [ 53,  89,  69,  91,  56],
       [ 56,  82,  72,  76,  84],
       [ 67,  51,  65,  71, 100],
       [ 70,  54,  73, 100,  90],
       [ 83,  99,  83,  81,  93],
       [ 98,  86,  68,  84,  99],
       [100,  78,  82, 100,  85],
       [100,  73,  79,  71,  87],
       [ 65,  79,  68,  74,  56],
       [ 86,  96,  84,  73,  62],
       [ 55,  95,  87,  54,  57],
       [ 94,  70,  51,  64,  76],
       [ 82,  63,  82,  67,  59],
       [100,  77,  92,  63,  77],
       [ 56,  72,  57,  74,  56],
       [ 75,  52,  89,  71,  94],
       [ 60,  93,  74,  79,  65],
       [ 78,  56,  93,  70,  77],
       [ 61,  65,  83,  88,  70],
       [ 63,  96,  50,  95,  74],
       [ 86,  73,  60,  97, 100],
       [ 51,  89,  59,  71,  96],
       [ 69,  80,  54,  53,  61],
       [ 96,  88,  61,  58, 100],
       [ 62,  78,  54,  74,  53],
       [ 50,  69,  57,  91,  80],
       [ 58,  92,  89,  95,  55],
       [ 90,  67,  78,  51,  54],
       [ 96,  97,  75,  69,  65],
       [ 99,  99,  72,  97,  57],
       [ 91,  87,  54,  65,  78],
       [ 72,  58,  62,  61,  63],
       [ 68,  74,  76,  77,  84],
       [ 73,  90,  85,  99,  62],
       [100,  76,  83,  84,  52],
       [ 56,  65,  68,  70,  89],
       [ 83,  70,  91,  60,  64],
       [ 55,  94,  60,  54,  51],
       [ 68,  52,  78,  51,  69],
       [ 87,  76,  85,  92,  60],
       [ 73,  87,  90,  67,  89]], dtype=int32)

In [2]:
#學生成績單

import numpy as np
import pandas as pd

scores = np.random.randint(50, 101, size=(50, 5))
scores_pd = pd.DataFrame(scores,columns=['國文','英文','數學','地理','歷史'],index=range(1,51))
scores_pd.T

,1,2,3,4,5,6,7,8,9,10,...,41,42,43,44,45,46,47,48,49,50
國文,99,56,68,89,100,51,100,92,74,76,...,80,72,79,63,81,80,51,70,89,83
英文,99,84,69,74,58,78,76,69,71,62,...,73,52,74,87,99,76,64,86,65,81
數學,97,86,95,64,84,50,79,92,72,91,...,80,93,79,97,79,58,55,81,70,59
地理,62,96,100,76,78,76,98,99,85,83,...,94,93,60,90,79,96,72,77,98,70
歷史,100,92,77,88,70,92,73,96,80,51,...,60,57,84,99,55,96,78,90,89,94

In [ ]:
#學生成績單

import numpy as np
import pandas as pd

scores = np.random.randint(50, 101, size=(50, 5))
scores_pd = pd.DataFrame(scores,columns=['國文','英文','數學','地理','歷史'],index=range(1,51))
scores_pd.T

In [ ]:
scores_pd.index.name = "學號"
scores_pd.columns.name = "科目"
sum_value = scores_pd.sum(axis=1)
mean_value = np.mean(scores_pd,axis=1)

In [ ]:
scores_pd['總分'] = sum_value
scores_pd['平均'] = mean_value

In [ ]:
scores_pd

In [8]:
#排序
scores_pd1 = scores_pd.sort_values(by='總分',ascending=False)
scores_pd1

科目  國文   英文   數學   地理  歷史   總分    平均
學號
43  96   94   98   90  85  463  92.6
7   89   94   98   77  95  453  90.6
17  67   99   84   84  90  424  84.8
24  81   87   66   89  98  421  84.2
4   95   82   56   96  88  417  83.4
1   86   72  100   80  79  417  83.4
18  74   88   62   95  91  410  82.0
2   91  100   89   57  67  404  80.8
41  92   80   85   90  54  401  80.2
12  74   71   88   71  91  395  79.0
32  90   62   79   89  75  395  79.0
11  90   83   71   55  94  393  78.6
42  75   80   71   79  88  393  78.6
22  67   68   65   99  91  390  78.0
19  80   91   59   84  72  386  77.2
38  91   51   80   91  73  386  77.2
40  52   94   79   89  72  386  77.2
14  82   70   87   73  73  385  77.0
25  59   99   55   96  76  385  77.0
5   61   88   76   73  86  384  76.8
16  59   74   87   67  96  383  76.6
8   68   58   92   74  87  379  75.8
34  78   57   80   65  97  377  75.4
10  90   86   70   53  77  376  75.2
30  83   82   53   75  79  372  74.4
35  55   86   65   81  83  370  74.0
3   65   52   89   71  90  367  73.4
50  53   95   74   81  64  367  73.4
33  55   88   61   90  70  364  72.8
36  60   71   77  100  55  363  72.6
49  53   72   86   96  55  362  72.4
44  63   88   76   79  54  360  72.0
46  53   90   93   64  53  353  70.6
21  75   79   53   65  78  350  70.0
27  59   60   60   85  84  348  69.6
48  99   65   53   54  76  347  69.4
39  57   86   52   70  81  346  69.2
26  59   73   57   97  60  346  69.2
20  75   68   55   85  62  345  69.0
23  66   73   52   52  97  340  68.0
9   84   81   50   60  64  339  67.8
37  77   60   69   60  69  335  67.0
47  56   64   78   54  73  325  65.0
6   63   56   62   71  71  323  64.6
15  55   80   55   53  72  315  63.0
28  77   59   61   52  61  310  62.0
13  51   52   64   70  69  306  61.2
31  77   57   51   50  69  304  60.8
45  59   50   58   69  67  303  60.6
29  70   50   52   73  53  298  59.6

In [ ]:
#排名
scores_pd1['排名'] = scores_pd1['總分'].rank(axis=0,method='min',ascending=False)

In [ ]:
scores_pd1
scores_pd1.iloc[-5:]

In [ ]:
def calulate(s):
    #return 自訂的series
    custom_series = pd.Series([s.min(),s.max(),s.median(),s.std()],index=["最低分數","最高分數","中間值","標準差"])
    return custom_series
scores_pd1.iloc[:,:5].apply(calulate)

In [ ]:
def calulate1(s):
    #return 自訂的series
    s_bool = s < 60
    return s_bool.sum()

scores_pd1["不及格的課目"] = scores_pd1.iloc[:,:5].apply(calulate1,axis=1)

In [ ]:
scores_pd1