https://www.perplexity.ai/search/cea283c5-8750-41ff-8811-20ec42b77262

In [32]:
import requests
from requests import ConnectionError,HTTPError,Timeout
import numpy as np
import pandas as pd

url = 'https://data.ntpc.gov.tw/api/datasets/010e5b15-3823-4b20-b401-b1cf000550c5/json?page=0&size=1000'
try:
    response = requests.get(url)    
    response.raise_for_status()    
except ConnectionError:
    print('找不到伺服器')
except HTTPError:
    print('網頁找不到')
except Timeout:
    print('超過時間沒有回應')
else:
    print('沒有發生問題')

records = response.json()
#records
allRecords = pd.DataFrame(records,columns=['sna','tot','mday','sbi','sarea','ar','bemp'])
allRecords1 = allRecords.rename(columns= {'sna':'站名', 'sarea':'區域', 'ar':'地址', 'tot':'數量','sbi':'可借', 'bemp':'可還','mday':'時間'})

沒有發生問題

In [33]:
allRecords1['站名'] = allRecords1['站名'].apply(lambda name:name[11:])

In [34]:
allRecords1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   站名      1000 non-null   object
 1   數量      1000 non-null   object
 2   時間      1000 non-null   object
 3   可借      1000 non-null   object
 4   區域      1000 non-null   object
 5   地址      1000 non-null   object
 6   可還      1000 non-null   object
dtypes: object(7)
memory usage: 54.8+ KB

In [35]:
allRecords1['時間'] = pd.to_datetime(allRecords1['時間'])

In [36]:
allRecords1[['數量','可借','可還']] = allRecords1[['數量','可借','可還']].astype(int)

In [37]:
allRecords1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   站名      1000 non-null   object
 1   數量      1000 non-null   int64
 2   時間      1000 non-null   datetime64[ns]
 3   可借      1000 non-null   int64
 4   區域      1000 non-null   object
 5   地址      1000 non-null   object
 6   可還      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 54.8+ KB

In [38]:
import numpy as np
grouped = allRecords1.groupby('區域')
agg_df = grouped[['數量','可借','可還']].agg([("加總","sum"),("平均","mean"),("中間數","median"),("最多","max"),("最少","min")])

In [39]:
agg_df

       數量                             可借                           可還  \
       加總         平均   中間數  最多  最少    加總         平均  中間數  最多 最少    加總
區域
三峽區  1540  22.318841  20.0  63  10   654   9.478261  8.0  27  1   886
三芝區   170  21.250000  16.0  48  14    50   6.250000  6.0  14  2   120
三重區  3774  30.435484  28.5  95  11  1277  10.298387  8.0  84  0  2414
中和區  3483  33.490385  30.0  99  10  1297  12.471154  8.0  89  0  2148
五股區   667  22.233333  20.0  48  13   216   7.200000  6.5  18  0   449
八里區   533  21.320000  20.0  46  13   105   4.200000  2.0  22  0   425
土城區  2828  32.136364  30.0  94   9   764   8.681818  6.0  60  0  1990
坪林區    65  21.666667  22.0  23  20     8   2.666667  2.0   5  1    57
平溪區   174  34.800000  30.0  55  20    29   5.800000  6.0  10  1   145
板橋區  7366  36.107843  34.0  99   9  2085  10.220588  6.0  77  0  5060
林口區  2233  26.583333  23.5  99  10   827   9.845238  9.0  52  0  1393
永和區  1548  28.145455  23.0  79  10   434   7.890909  5.0  31  0  1076
汐止區  2397  32.391892  28.5  99   9   981  13.256757  8.0  74  0  1383
泰山區   668  26.720000  22.0  45  12   237   9.480000  8.0  23  0   428
淡水區  2073  25.912500  21.0  98  10   642   8.025000  6.0  33  0  1410
深坑區   109  21.800000  18.0  34  12    14   2.800000  2.0   6  1    95
烏來區    28  28.000000  28.0  28  28     4   4.000000  4.0   4  4    24
石碇區    52  17.333333  15.0  23  14    18   6.000000  8.0   9  1    34
石門區   102  34.000000  26.0  56  20    16   5.333333  6.0   7  3    86
貢寮區    60  20.000000  20.0  20  20    20   6.666667  4.0  13  3    40
金山區   163  23.285714  24.0  30  15    41   5.857143  6.0  10  2   122


            平均   中間數  最多  最少
區域
三峽區  12.840580  10.0  44   2
三芝區  15.000000  14.0  42   0
三重區  19.467742  17.0  79   2
中和區  20.653846  16.5  57   2
五股區  14.966667  13.5  47   5
八里區  17.000000  13.0  45   9
土城區  22.613636  20.0  61   2
坪林區  19.000000  20.0  22  15
平溪區  29.000000  29.0  50  10
板橋區  24.803922  22.5  89   0
林口區  16.583333  14.0  93   2
永和區  19.563636  16.0  59   0
汐止區  18.689189  15.0  74   0
泰山區  17.120000  14.0  40   1
淡水區  17.625000  16.0  61   2
深坑區  19.000000  16.0  31   9
烏來區  24.000000  24.0  24  24
石碇區  11.333333  14.0  14   6
石門區  28.666667  20.0  53  13
貢寮區  13.333333  16.0  17   7
金山區  17.428571  15.0  28   8

In [40]:
agg_df.columns.names = ["租借","統計"]
s1 = agg_df.stack(level=['租借','統計'],future_stack=True)
s1

區域   租借  統計
三峽區  數量  加總     1540.000000
         平均       22.318841
         中間數      20.000000
         最多       63.000000
         最少       10.000000
                   ...
金山區  可還  加總      122.000000
         平均       17.428571
         中間數      15.000000
         最多       28.000000
         最少        8.000000
Length: 315, dtype: float64

In [41]:
s1.unstack(level="統計")

統計          加總         平均   中間數    最多    最少
區域  租借
三峽區 數量  1540.0  22.318841  20.0  63.0  10.0
    可借   654.0   9.478261   8.0  27.0   1.0
    可還   886.0  12.840580  10.0  44.0   2.0
三芝區 數量   170.0  21.250000  16.0  48.0  14.0
    可借    50.0   6.250000   6.0  14.0   2.0
...        ...        ...   ...   ...   ...
貢寮區 可借    20.0   6.666667   4.0  13.0   3.0
    可還    40.0  13.333333  16.0  17.0   7.0
金山區 數量   163.0  23.285714  24.0  30.0  15.0
    可借    41.0   5.857143   6.0  10.0   2.0
    可還   122.0  17.428571  15.0  28.0   8.0

[63 rows x 5 columns]